### PR TITLE
adopt yargsParser directly for chromeFlags parsing

### LINKED ISSUE #3003: --chrome-flags="--no-sandbox" Runtime error
Getting the following error when using lighthouse@2.4.0 (cli)

```
Could not execute test.  { Error: Command failed: lighthouse http://www.google.com 	--chrome-flags="--headless --disable-gpu --no-sandbox --allow-running-insecure-content --ignore-certificate-errors" 	--output json 	--perf 	--disable-cpu-throttling 	--disable-device-emulation 	--save-assets 	--save-artifacts 	--output-path=//lighthouse-report/perf.out
Runtime error encountered: TypeError: value.indexOf is not a function
    at formatArg (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:35:15)
    at allKeys.filter.map.k (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:19)
    at Array.map (<anonymous>)
    at parseChromeFlags (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:10)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:57:26
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:12:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:8:12)
    at getDebuggableChrome (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:54:12)
TypeError: value.indexOf is not a function
    at formatArg (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:35:15)
    at allKeys.filter.map.k (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:19)
    at Array.map (<anonymous>)
    at parseChromeFlags (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:10)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:57:26
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:12:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:8:12)
    at getDebuggableChrome (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:54:12)
```

Reduced to `--chrome-flags="--no-sandbox"`:

```
lighthouse http://www.google.com --chrome-flags="--no-sandbox"
Runtime error encountered: TypeError: value.indexOf is not a function
    at formatArg (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:35:15)
    at allKeys.filter.map.k (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:19)
    at Array.map (<anonymous>)
    at parseChromeFlags (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:10)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:57:26
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:12:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:8:12)
    at getDebuggableChrome (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:54:12)
TypeError: value.indexOf is not a function
    at formatArg (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:35:15)
    at allKeys.filter.map.k (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:19)
    at Array.map (<anonymous>)
    at parseChromeFlags (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:46:10)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:57:26
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:12:71
    at Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:8:12)
    at getDebuggableChrome (/usr/local/lib/node_modules/lighthouse/lighthouse-cli/run.js:54:12)
```

```
google-chrome --version
Google Chrome 60.0.3112.101 
```

Same commands works with lighthouse@2.3.0
```
lighthouse --version && lighthouse http://www.google.com --chrome-flags="--no-sandbox"
2.3.0
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +512ms
  ChromeLauncher Waiting for browser.....✓ +3ms
  Lighthouse:warn The URL provided should be on HTTPS +132ms
  Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS. +0ms
  status Initializing… +588ms
  status Loading page & waiting for onload URL, Viewport, ViewportDimensions, ThemeColor, Manifest, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL +391ms
...
```
lighthouse@2.3.0
```
lighthouse --version && lighthouse http://www.google.com --chrome-flags="--headless --disab
le-gpu --no-sandbox" --output json --perf true --disable-cpu-throttling --disable-device-emulation --save-assets --save-artifacts --output-p
ath=./lighthouse-report/perf.out
2.3.0
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +515ms
  ChromeLauncher Waiting for browser.....✓ +3ms
  Lighthouse:warn The URL provided should be on HTTPS +82ms
  Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS. +0ms
  status Initializing… +390ms
  status Loading page & waiting for onload ViewportDimensions, ImageUsage, DOMStats, OptimizedImages, ResponseCompression, TagsBlockingFirstPaint +333ms
...
```

### PR DESCRIPTION
**Pull request by paulirish**
yargs has some overzealous parsing. by using yargs-parser directly, we can turn off boolean & camelCasing. Still have to add back quotes, but it doesn't seem too bad.

basically the alternative impl of #2754 (which was for #2753)

fixes #3003

### CODE REVIEW

File: lighthouse-cli/run.ts [hunk 1]
```diff
@@ -29,28 +29,23 @@ interface LighthouseError extends Error {
...
 // exported for testing
 export function parseChromeFlags(flags: string) {
-  let args = yargs(flags).argv;
-  const allKeys = Object.keys(args);
-
-  // Remove unneeded arguments (yargs includes a _ arg, $-prefixed args, and camelCase dupes)
-  return allKeys.filter(k => k !== '_' && !k.startsWith('$') && !/[A-Z]/.test(k))
-      .map(k => formatArg(k, args[k]));
+  const parsed = yargsParser(
+      flags || '', {configuration: {'camel-case-expansion': false, 'boolean-negation': false}});
```
Comment (brendankenny) [inline lighthouse-cli/run.ts]: for `flags` here, seems like this is broken type checking? If it's a string the only falsy value is already `''`

could either initialize a default value in `getDebuggableChrome` or do `flags = ''` as the parameter default

File: lighthouse-cli/test/cli/run-test.js [hunk 2]
```diff
@@ -58,8 +58,21 @@ describe('Parsing --chrome-flags', () => {
     assert.deepStrictEqual([], parseChromeFlags());
   });
 
+  it('keeps --no-flags untouched, #3003', () => {
+    assert.deepStrictEqual(['--no-sandbox'], parseChromeFlags('--no-sandbox'));
```
Comment (brendankenny) [inline lighthouse-cli/test/cli/run-test.js]: any reason these are backwards from the usual actual/expected order?

File: lighthouse-cli/test/cli/run-test.js [hunk 3]
```diff
@@ -58,8 +58,21 @@ describe('Parsing --chrome-flags', () => {
...
+  });
+
+  it('handles numeric values', () => {
+    assert.deepStrictEqual(['--log-level=0'], parseChromeFlags('--log-level=0'));
+  });
+
   it('returns flags correctly for issue 2817', () => {
```
Comment (brendankenny) [inline lighthouse-cli/test/cli/run-test.js]: while you're in here, mind adding something like `it('quotes flag values with spaces in them'), () => {` or whatever (rather than just "issue 2817") :)

File: lighthouse-cli/test/cli/run-test.js (hunk 2 above)
Comment (patrickhulce) [reply lighthouse-cli/test/cli/run-test.js]: I didn't notice that the first time around here, but I was just wondering the same haha

Comment (paulirish) [reply lighthouse-cli/test/cli/run-test.js]: yes will happily swap them. it was breaking my brain too.
i blame the other guy.

File: lighthouse-cli/run.ts [hunk 4]
```diff
@@ -29,28 +29,23 @@ interface LighthouseError extends Error {
...
+      (typeof str === 'string' && str.includes(' ')) ? `"${str}"` : str;
+
+  return Object
+      .keys(parsed)
+      // Remove unnecessary _ item provided by yargs,
+      .filter(key => key !== '_')
+      // Avoid '=true', then reintroduce quotes if required
+      .map(key => {
+        if (parsed[key] === true) return `--${key}`;
+        return `--${key}=${addQuotes(parsed[key])}`;
```
Comment (patrickhulce) [inline lighthouse-cli/run.ts]: nit: not sure this is worth creating a function for anymore since it's not used anywhere else and only handles the one case now

aside: does it do any harm to quote the value if it doesn't contain spaces?

Comment (paulirish) [reply lighthouse-cli/run.ts]: > aside: does it do any harm to quote the value if it doesn't contain spaces?

it does yes. tested this out. i think.

Comment (paulirish) [reply lighthouse-cli/run.ts]: > nit: not sure this is worth creating a function for anymore

pshhhh... there was a ToTT about this before! 
I would prefer having a clear name for this simple line than mentally parse it each time i reread the source.

Comment (paulirish) [reply lighthouse-cli/run.ts]: perma-quoting now. :)
