### PR TITLE
deps: update marky to latest

### LINKED ISSUE #12439: TypeError: perf.getEntriesByName is not a function
When updating node from 15 to 16 and running lighthouse I get this error:
```
TypeError: perf.getEntriesByName is not a function
    at Object.exports.stop (.../node_modules/marky/lib/marky.cjs.js:55:24)
    at Function.timeEnd (.../node_modules/lighthouse-logger/index.js:128:11)
    at Function.requireGatherers (.../node_modules/lighthouse/lighthouse-core/config/config.js:815:9)
    at new Config (.../node_modules/lighthouse/lighthouse-core/config/config.js:342:27)
    at generateConfig (.../node_modules/lighthouse/lighthouse-core/index.js:60:10)
    at lighthouse (.../node_modules/lighthouse/lighthouse-core/index.js:43:18)
    at runLighthouse (.../node_modules/lighthouse/lighthouse-cli/run.js:224:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```
Lighthouse-logger seems to use [marky@1.2.0](https://github.com/GoogleChrome/lighthouse/blob/2614e710ef7d7d66bcfd9209e4a8d331a23fd33f/lighthouse-logger/package.json#L7) which is using a [deprecated performance method getEntriesByName](https://github.com/nodejs/node/issues/21621).

### PR DESCRIPTION
**Pull request by brendankenny**
fixes #12439 (but really just for contributors)

See https://github.com/nolanlawson/marky/issues/18 for the issue in node 16 (introduced in https://github.com/nodejs/node/pull/37970).

However as noted by @patrickhulce in https://github.com/GoogleChrome/lighthouse-ci/issues/596#issuecomment-832006808, `lighthouse-logger` currently uses `marky@^1.2.0`, so any downstream project just needs to refresh their deps and they'll pick up 1.2.2.

However, contributors (with a git repo checkout) _are_ subject to our `yarn.lock` files for dependencies, so we do need to update those for us.

### CODE REVIEW

File: lighthouse-logger/yarn.lock [hunk 1]
```diff
@@ -2,16 +2,17 @@
 # yarn lockfile v1
 
 
-debug@^2.6.8:
+debug@^2.6.9:
```
Comment (brendankenny) [inline lighthouse-logger/yarn.lock:5]: weird that the package.json version and actual version in here got bumped in #9398 but this line didn't 🤷

**Review by adamraine — APPROVED** [review]
