### ISSUE TITLE
TypeError: perf.getEntriesByName is not a function

### ISSUE THREAD

**Issue by MarcLlobet** [GoogleChrome/lighthouse#12439]
When updating node from 15 to 16 and running lighthouse I get this error:
```
TypeError: perf.getEntriesByName is not a function
    at Object.exports.stop (.../node_modules/marky/lib/marky.cjs.js:55:24)
    at Function.timeEnd (.../node_modules/lighthouse-logger/index.js:128:11)
    at Function.requireGatherers (.../node_modules/lighthouse/lighthouse-core/config/config.js:815:9)
    at new Config (.../node_modules/lighthouse/lighthouse-core/config/config.js:342:27)
    at generateConfig (.../node_modules/lighthouse/lighthouse-core/index.js:60:10)
    at lighthouse (.../node_modules/lighthouse/lighthouse-core/index.js:43:18)
    at runLighthouse (.../node_modules/lighthouse/lighthouse-cli/run.js:224:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```
Lighthouse-logger seems to use [marky@1.2.0](https://github.com/GoogleChrome/lighthouse/blob/2614e710ef7d7d66bcfd9209e4a8d331a23fd33f/lighthouse-logger/package.json#L7) which is using a [deprecated performance method getEntriesByName](https://github.com/nodejs/node/issues/21621).

**Comment by patrickhulce** [comment]
As noted in https://github.com/GoogleChrome/lighthouse-ci/issues/596#issuecomment-832006808 @MarcLlobet this isn't a Lighthouse issue. The version marker is already flexible enough that it will install 1.2.2 if you aren't using a lockfile already (in which case its on the owner of the lockfile to update).
