### ISSUE TITLE
"Ni.connect is not a function" when testing in DevTools

### ISSUE THREAD

**Issue by hculp** [GoogleChrome/lighthouse#15300]
**Developer's Note**

This has likely been fixed in Chrome Canary, but still present in current stable release (115). Please only comment about your case if you are on Chrome 117 or later.

______

### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://mini-project-lighthouse.herokuapp.com/

### What happened?

When trying to run an audit, received an error and was unable produce an audit. Sometimes and audit would work, but only the PWA audit report was displayed/created.

### What did you expect?

Expected to generate a full audit report. All audit settings selected. Only the PWA section was generated sometimes. Issues replicated in incognito. 

### What have you tried?

Using latest chrome browser, restarted browser, removed/re-installed extension, and allowed incognito extension use.

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

100.0.0

### Chrome Version

115.0.5790.102

### OS

Windows 10

### Relevant log output

```shell
Ni.connect is not a function

Channel: DevTools
Initial URL: https://mini-project-lighthouse.herokuapp.com/
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:3056)
```
```

**Comment by lms11** [comment]
+1

**Comment by adamraine** [comment]
I haven't reproduced this issue yet on Windows, but there might be enough to investigate on in your log output. Will keep an eye out for this as it probably started in M115.

**Comment by lucasnetau** [comment]
This started occurring for me after updating to Version 115.0.5790.102 (Official Build) (x86_64), MacOS 13.4, all Lighthouse modes unavailable.

When mode = **Navigation**:

Ni.connect is not a function
```
Channel: DevTools
Initial URL: https://xxx
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:3056)
```

When mode = **Timespan**, notification of timespan started and you can interact with the page, however on stopping the following is thrown:

Cannot end a timespan before starting one
```
Channel: DevTools
Initial URL: https://xxx
Chrome Version: 115.0.0.0
Stack Trace: Error: Cannot end a timespan before starting one
    at i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:976)
    at self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:3062)
```

When mode = **Snapshot**

Cannot read properties of null (reading 'target')
```
Channel: DevTools
Initial URL: https://xxx
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Cannot read properties of null (reading 'target')
    at Driver.connect (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:603:762)
    at snapshotGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:621:282)
    at async snapshot (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:621:88)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:2446)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4090efd4b0ad6aa15eeafcdabd5817ae939f7ba059%2F:1:3056)
```

**Comment by lucasnetau** [comment]
Sorry for noise, a further update to Version 115.0.5790.114 (Official Build) (x86_64) and the issue has resolved

**Comment by lms11** [comment]
It did fix for me (I was having the same issue).

**Comment by hculp** [comment]
After updating to Version 115.0.5790.110 on chrome, the issue appears to have resolved.

**Comment by frankli0324** [comment]
I'm running into the same error on 115.0.5790.114

**Comment by CoreyDotCom** [comment]
This issue is biting me a ton on various internal projects here at Adobe.   115.0.5790.114 ...

**Comment by CoreyDotCom** [comment]
Confirmed fixed by latest Canary M117.

**Comment by sergromanenko1** [comment]
My current version of Chrome is 115.0.5790.110 and I had the same problem.
After uninstalling and reinstalling, the problem disappeared.

**Comment by adamraine** [comment]
I can't reproduced this, but it appears that this error is being thrown here:

https://github.com/GoogleChrome/lighthouse/blob/113bd76598c8ddcd1af258b8f3f8447ec78a6768/core/gather/navigation-runner.js#L354-L356

We shouldn't be entering this code path because the `page` is provided by the DevTools environment. So for some reason we are passing an invalid `page` value into Lighthouse.

**Comment by gabycperezdias** [comment]
I am on windows, Chrome Version 115.0.5790.110 (Official Build) (64-bit) and I am able to reproduce this

**Comment by JustLukes** [comment]
Running Chrome Version 115.0.5790.110 and I get this issue every time

**Comment by CoreyDotCom** [comment]
Please see the thread … the issue has been fixed. :)

**Comment by gabycperezdias** [comment]
@CoreyDotCom I am sorry, I am going to my Chrome and I cannot update further than that, so you said the issue is fixed, I am assuming on version `...114` but, how am I able to update to that version?

**Comment by adamraine** [comment]
If you need to use a version later than the current stable Chrome then you can install [Chrome canary](https://www.google.com/chrome/canary/).

This issue is only present in the DevTools version of Lighthouse so you can also use the Lighthouse CLI or PageSpeed insights.

**Comment by Sarwarhridoy4** [comment]
Ni.connect is not a function
```
Channel: DevTools
Initial URL: https://sarwar-hossain.netlify.app/
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%405e87dfef0c85687ea835e444d33466745cc0725f%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%405e87dfef0c85687ea835e444d33466745cc0725f%2F:1:3056)
```

This happens to me while trying to audit in incognito window.

**Comment by rizypb** [comment]
After updating Google Chrome to 115.0.5790.170 the issue has been resolved 👍

**Comment by MSAJAL07** [comment]
Getting same error-

`Ni.connect is not a function
```
Channel: DevTools
Initial URL: http://localhost:3000/home
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4067277e15806bf7f0307b37cd6f8f29e71b615796%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4067277e15806bf7f0307b37cd6f8f29e71b615796%2F:1:3056)
````

**Comment by paulirish** [comment]
Hi. Dev here.
We're having trouble reproducing this so.. if you want to poke around.. we'd appreciate some more debugging details.

Unfortunately since we run lighthouse in a webworker.. this is not trivial debugging.

1. undock devtools. ctrl-shift-i to inspect devtools.  now you have devtools on devtools (we'll call this DoD). optionally redock the first devtools.
1. in DoD, ctrl-o and look for lighthouse.js  place a breakpoint within initWorker's onmessage callback
![image](https://github.com/GoogleChrome/lighthouse/assets/39191/e75a6fdc-3e96-491c-aafc-48284ec8581b)
1. in page DevTools, start Lighthouse with 'Analyze Page Load' the DoD debugger should pause on your new breakpoint
1. You can now remove the breakpoint (otherwise it'll get annoying)
1. you should also now see a lighthouse_worker.js in DoD threads now: 
![image](https://github.com/GoogleChrome/lighthouse/assets/39191/8a520d0a-49e2-4ee6-93e0-29ad8594ee50)
1. in the DoD, ctrl-o for `puppeteer.js`, go to the very bottom and place a breakpoint on the return statement: 
![image](https://github.com/GoogleChrome/lighthouse/assets/39191/5c18cf72-1db2-42ec-9ce2-abe04eb92bc1)
1. resume script execution. you should pause on the new breakpoint
1. log out `e`
1. log out `l.pages().then(pages => console.warn(pages.length))`
1. resume and view the last log

**Comment by Larry0ua** [comment]
Same Ni.connect is not a function issue reproduced for me on Chrome Version 115.0.5790.171 (Official Build) (64-bit)
Going through steps above from @paulirish I see the next:
```
> e
< {connection: t, mainFrameId: 'D488FDD86D9EF4DD52A8541E9181A48A', targetInfos: Array(58), targetFilterCallback: ƒ, isPageTargetCallback: ƒ}
> l.pages().then(pages => console.warn(pages.length))
< Promise {<pending>}
(resumed debugging)
> 0
< lighthouse.js:58 TypeError: Ni.connect is not a function
    at ://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40cc0d30c2ca5577520c8646671513241faa0bc105%2F:1:2668)
    at async self.onmessage (://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40cc0d30c2ca5577520c8646671513241faa0bc105%2F:1:3056)```

Anything more I can do to help with debugging? Actually it only reproduces with only one specific website to me, so maybe the issue is input-related. Should I share the website link to anyone?

**Comment by adamraine** [comment]
We've landed a potential fix in Chrome Canary and are working on upstreaming the change to M116 and M117:
https://bugs.chromium.org/p/chromium/issues/detail?id=1472050

**Comment by JaRoMasterDev** [comment]
I am facing the same issue. For me (Windows) the error is only occuring in incognito mode

**Comment by Tilesto** [comment]
The same error

Mi.connect is not a function
```
Channel: DevTools
Initial URL: https://cyberstore-dev.site/ru
Chrome Version: 116.0.0.0
Stack Trace: TypeError: Mi.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:3056)
```


MacOS, Version 116.0.5845.96 (Official Build) (arm64)

**Comment by Lilysunstrider** [comment]
same as above. now have `Mi.connect is not a function` error
```
Channel: DevTools
Initial URL: <some_url>
Chrome Version: 116.0.0.0
Stack Trace: TypeError: Mi.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:3056)
```
MacOS 13.4.1

**Comment by left0ver** [comment]
> 

metoo,MacOs 12.5 ,Chrome version 116.0.5845.96

**Comment by left0ver** [comment]
> same as above. now have `Mi.connect is not a function` error
> 
> ```
> Channel: DevTools
> Initial URL: <some_url>
> Chrome Version: 116.0.0.0
> Stack Trace: TypeError: Mi.connect is not a function
>     at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
>     at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
>     at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
>     at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
>     at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:2668)
>     at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:3056)
> ```
> 
> MacOS 13.4.1

metoo,MacOs 12.5 ,Chrome version 116.0.5845.96

**Comment by KatarzynaChmielecka** [comment]
windows 10, chrome 116.0.5845.111 -the same as others... Mi.connect is not a function, in incognito mode

**Comment by ScottAgirs** [comment]
SOLVED (for me) - by restarting Chrome.

**Comment by adamraine** [comment]
Hey folks, the fix for this should be released on all Chrome channels:

Stable - 116.0.5845.140
Beta - 117.0.5938.35
Dev - 118.0.5951.0
Canary - 118.0.5939.0

If you are still experiencing this issue, please verify that your Chrome is up to date before reporting.

**Comment by supersuryaansh** [comment]
I am on Vivaldi, and the error persists.

**Comment by adamraine** [comment]
We do not officially support Vivaldi, please file a bug with that browser.

**Comment by dransome** [comment]
> I am on Vivaldi, and the error persists.

To avoid other Vivaldi users repeating my work, I have filed a report relating to this issue with Vivaldi: VB-99984
